# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/python-3.6.13-on-linux_64, last modified Tue Feb 23 20:42:09 2021
# ------------------------------------------------

package:
  name: python
  version: 3.6.13
source:
  - patches:
      - 0001-Add-Anaconda-Distribution-version-logic.patch
      - 0002-Darwin-Omit-PYTHONFRAMEWORK-site-packages.patch
      - 0003-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
      - 0004-Win32-distutils-Also-look-for-executable.bat.patch
      - 0005-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - 0006-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
      - 0007-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
      - 0008-Support-cross-compiling-byte-code.patch
      - 0009-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
      - 0010-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
      - 0011-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - 0012-Win32-Do-not-download-externals.patch
      - 0013-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
      - 0014-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - 0015-Disable-new-dtags-in-unixccompiler.py.patch
      - 0016-Fix-cross-compilation-on-Debian-based-distros.patch
      - 0017-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - 0018-Unvendor-sqlite3.patch
    sha256: a47a43a53abb42286a2c11965343ff56711b9e64e8d11bf2c6701a4fb8ce1a0f
    url: https://www.python.org/ftp/python/3.6.13/Python-3.6.13.tar.xz
build:
  detect_binary_files_with_prefix: false
  ignore_run_exports:
    - bzip2
  no_link:
    - bin/python3.6
  number: '0'
  string: hdb3f193_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - binutils_impl_linux-64 2.33.1 he6710b0_7
    - binutils_linux-64 2.33.1 h9595d00_15
    - gcc_impl_linux-64 7.3.0 habb00fd_1
    - gcc_linux-64 7.3.0 h553295d_15
    - gxx_impl_linux-64 7.3.0 hdf63c60_1
    - gxx_linux-64 7.3.0 h553295d_15
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
    - libx11-cos6-x86_64 1.6.4 h64a1553_0
    - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
    - make 4.2.1 h1bed415_1
    - pkg-config 0.29.2 h1bed415_8
    - xorg-x11-proto-devel-cos6-x86_64 7.7 h8d4a98b_0
  host:
    - _libgcc_mutex 0.1 main
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2021.1.19 h06a4308_0
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libedit 3.1.20191231 h14c3975_1
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1j h27cfd23_0
    - readline 8.0 h7b6447c_0
    - sqlite 3.33.0 h62c20be_0
    - tk 8.6.10 hbc83047_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - ld_impl_linux-64
    - libffi >=3.3,<3.4.0a0
    - libgcc-ng >=7.3.0
    - libstdcxx-ng >=7.3.0
    - ncurses >=6.2,<7.0a0
    - openssl >=1.1.1j,<1.1.2a
    - readline >=8.0,<9.0a0
    - sqlite >=3.33.0,<4.0a0
    - tk >=8.6.10,<8.7.0a0
    - xz >=5.2.5,<6.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - python -V
    - python3 -V
    - 2to3 -h
    - pydoc -h
    - python3-config --help
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - _CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
      python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
about:
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  dev_url: https://docs.python.org/devguide/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  doc_url: https://www.python.org/doc/versions/
  home: http://www.python.org/
  license: PSF
  license_file: LICENSE
  summary: General purpose programming language
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
