# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Thu Oct  8 19:13:45 2020
# ------------------------------------------------

package:
    name: sqlparse
    version: 0.4.1
source:
    sha256: 0f91fd2e829c44362cbcfab3e9ae12e22badaa8a29ad5ff599f9ec109f0454e8
    url: https://pypi.io/packages/source/s/sqlparse/sqlparse-0.4.1.tar.gz
build:
    entry_points:
        - sqlformat = sqlparse.__main__:main
    noarch: python
    number: '0'
    script: /tmp/build/80754af9/sqlparse_1602184451250/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1h h7b6447c_0
        - pip 20.2.3 py36_0
        - python 3.6.12 hcff3b4d_2
        - readline 8.0 h7b6447c_0
        - setuptools 50.3.0 py36hb0f4dca_1
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - wheel 0.35.1 py_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    commands:
        - pip check
    imports:
        - sqlparse
    requires:
        - pip
about:
    description: 'sqlparse is a non-validating SQL parser for Python. It provides
        support

        for parsing, splitting and formatting SQL statements.

        '
    dev_url: https://github.com/andialbrecht/sqlparse
    doc_url: https://sqlparse.readthedocs.org
    home: https://github.com/andialbrecht/sqlparse
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A non-validating SQL parser module for Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
